title: Sowmya S
logo: /assets/img/sowmya.jpg
description: 
  <p align="center">
  <a href="https://github.com/sowmya690">GitHub</a>
  
  <br>   
  I'm working on Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time GeoData location.
  Worked with Synchronoss technologies at Big Data Analytics team.
  Working in Rakuten in Bigdata and Geo Analytics domain for 3 years.
  <br>
  </p>


theme: jekyll-theme-minimal
