title: <p align="center"> Sowmya S </p>
logo: /assets/img/sowmya.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/sowmya-s-6a7823158/">LinkedIn</a> |
  <a href="https://github.com/sowmya690">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Geo location data.
  Worked with synchronoss technologies at Big Data Analytics team.
  Working in bigdata domain for 3 years.
  <br>
  </p>










theme: jekyll-theme-minimal
